# Generated by Django 5.2.3 on 2025-11-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_alter_ticket_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
